### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by cdw** [seismatica/ngram#2]
Hi @seismatica, this is a nice implementation! Would you consider adding a license file to enable reuse? Happy to do a PR if you'd prefer.

**Comment by KhanhNguyenHoma** [comment]
Hey @cdw ! Thank you for your appreciation 😄 

Yes please feel free to do the PR ! I've never had someone collaborating externally on one of my personal projects before, so don't hesitate to let me know what I can do to help.

I'm really curious what cool things you're trying to use my code for if you don't mind sharing, as this is the first time someone actually uses what I built for one of my personal projects !

**Comment by cdw** [comment]
Awesome! We've been experimenting with next token prediction for tool recommender systems, like what button are you likely to click next given what you've already used. Surprisingly, if you tokenize tool use, you've basically formulated the question as an NLP task! PR incoming

**Comment by lawi119** [comment]
Hi @seismatica - I am on the same team as @cdw . I tried to open up a PR against your repository but it looks like I am blocked from doing so. This is the LICENSE.txt file we were hoping to add to the root directory. It would allow us to build upon your work. Please let us know what you think and if you'd be open to adding this to your repository!

[LICENSE.txt](https://github.com/seismatica/ngram/files/14827143/LICENSE.txt)

**Comment by cdw** [comment]
Created PR: :-)  #3

**Comment by khanhnguyendata** [comment]
Merged ! Please feel free to share any updates you might have on this project. I'd really love to see that my code could contribute in some small way to your success 🎉 

PS. Are you guys also planning to do the n-gram interpolation mentioned in my blog post as well ? I could imagine scenarios where the next tool use depends not only on the tool used right before, but also the ones before that (without going too deep in the sequence and overfitting, hence the interpolation).

**Comment by cdw** [comment]
Hooray! We'll swing back for an update :-)
